export * from './createTemplate'
export * from './getTemplates'
export * from './updateTemplate'
export * from './deleteTemplate'
export * from './getTemplatesLwM2M'
export * from './getTemplateLwM2MById'