export * from './createTemplate'
export * from './getTemplates'
export * from './updateTemplate'
export * from './deleteTemplate'
export * from './createTemplateLwM2M'
export * from './updateTemplateLwM2M'
export * from './getTemplatesLwM2M'