import { Helmet } from 'react-helmet-async'

type HeadProps = {
  title?: string
  description?: string
}

export const Head = ({ title = '', description = '' }: HeadProps = {}) => {
  return (
    <Helmet
      title={title ? `${title} | IoT Platform` : undefined}
      defaultTitle="IoT Platform"
    >
      <meta name="description" content={description} />
      <link
        rel="icon"
        href="/android-icon-36x36.png"
        sizes="36x36"
        type="image/png"
      />
      <link
        rel="icon"
        href="/android-icon-48x48.png"
        sizes="48x48"
        type="image/png"
      />
      <link
        rel="icon"
        href="/android-icon-72x72.png"
        sizes="72x72"
        type="image/png"
      />
      <link
        rel="icon"
        href="/android-icon-96x96.png"
        sizes="96x96"
        type="image/png"
      />
      <link
        rel="icon"
        href="/android-icon-144x144.png"
        sizes="144x144"
        type="image/png"
      />
      <link
        rel="icon"
        href="/android-icon-192x192.png"
        sizes="192x192"
        type="image/png"
      />
      <link
        rel="icon"
        href="/favicon-16x16.png"
        sizes="16x16"
        type="image/png"
      />
      <link
        rel="icon"
        href="/favicon-32x32.png"
        sizes="32x32"
        type="image/png"
      />
      <link
        rel="icon"
        href="/favicon-96x96.png"
        sizes="96x96"
        type="image/png"
      />
      <link
        rel="apple-touch-icon"
        href="/apple-icon-57x57.png"
        sizes="57x57"
        type="image/png"
      />
      <link
        rel="apple-touch-icon"
        href="/apple-icon-60x60.png"
        sizes="60x60"
        type="image/png"
      />
      <link
        rel="apple-touch-icon"
        href="/apple-icon-72x72.png"
        sizes="72x72"
        type="image/png"
      />
      <link
        rel="apple-touch-icon"
        href="/apple-icon-76x76.png"
        sizes="76x76"
        type="image/png"
      />
      <link
        rel="apple-touch-icon"
        href="/apple-icon-114x114.png"
        sizes="114x114"
        type="image/png"
      />
      <link
        rel="apple-touch-icon"
        href="/apple-icon-120x120.png"
        sizes="120x120"
        type="image/png"
      />
      <link
        rel="apple-touch-icon"
        href="/apple-icon-144x144.png"
        sizes="144x144"
        type="image/png"
      />
      <link
        rel="apple-touch-icon"
        href="/apple-icon-152x152.png"
        sizes="152x152"
        type="image/png"
      />
      <link
        rel="apple-touch-icon"
        href="/apple-icon-180x180.png"
        sizes="180x180"
        type="image/png"
      />
      <link
        rel="mask-icon"
        href="/ms-icon-70x70.png"
        sizes="70x70"
        type="image/png"
      />
      <link
        rel="mask-icon"
        href="/ms-icon-144x144.png"
        sizes="144x144"
        type="image/png"
      />
      <link
        rel="mask-icon"
        href="/ms-icon-150x150.png"
        sizes="150x150"
        type="image/png"
      />
      <link
        rel="mask-icon"
        href="/ms-icon-310x310.png"
        sizes="310x310"
        type="image/png"
      />
      <link rel="icon" href="public/favicon.ico" />
      <link rel="manifest" href="public/manifest.json" />
    </Helmet>
  )
}
